### ISSUE TITLE
RenderDocumentToText adds an extra newline

### ISSUE THREAD

**Issue by seanomaly** [Athari/CsConsoleFormat#21]
If I do this `ConsoleRenderer.RenderDocument(doc);` I get the output as expected.
But if I do this:
`StringWriter sw = new StringWriter();`
vs `ConsoleRenderer.RenderDocumentAsText(doc, sw); `
and then `Console.WriteLine(sw.StringBuilder().toString());`
There is an extra `"\r\n"` between each line.

**Comment by seanomaly** [comment]
Thanks for the detailed explanation and the workaround.
I was using it as an optimization to output to a string and then calling Console.Write.
Using ConsoleRenderer.RenderDocument was just too slow.

On a related note, how do I get the output properly formatted on the command prompt? i.e. cmd.exe
I have been using conemu on which I get the formatting/color as expected but on cmd I just get a lot of junk characters.

**Comment by Athari** [comment]
Support issue is resolved. #22 and #23 should eventually make this workaround unnecessary.

**Comment by DumboJetEngine** [comment]
@Athari 
I try to output a table/grid in a file, using your code above, but it gets mangled up.
Code:
```
    var doc = new Document(grid);
    ConsoleRenderer.RenderDocument(doc); // Render in console.
    using var sw = new StringWriter() { NewLine = "\n" };
    ConsoleRenderer.RenderDocumentToText(doc, new TextRenderTarget(sw));
    var tableText = sw.GetStringBuilder().ToString();
    File.AppendAllText(logPath, tableText + "\r\n"); // Render in file.
```
It renders beautifully in the console :
![image](https://github.com/Athari/CsConsoleFormat/assets/8676903/9bbaa6a7-d807-4120-b07f-fe3981cf1dfc)
...but not in the file :
![image](https://github.com/Athari/CsConsoleFormat/assets/8676903/1755994a-8a68-421d-a12f-45097775f7b6)
It appears that there are some trailing spaces on the right, and the cell content is missing.
And there are also those weird vertical lines at the end, that I have no idea why they are there.
Any quick ideas are welcome, because I have tried playing with the `NewLine` parameter and other things, and I had zero luck so far.

**Comment by Athari** [comment]
@DumboJetEngine
Could you provide a [self-contained reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), so I could test it?

**Comment by DumboJetEngine** [comment]
@Athari 
Sure! :)
Here you go:
[Alba_CsConsoleFormat_Demo.zip](https://github.com/Athari/CsConsoleFormat/files/13429999/Alba_CsConsoleFormat_Demo.zip)

**Comment by Athari** [comment]
@DumboJetEngine 
Document objects aren't reusable. You need to recreate the document tree for each separate render.

As to spaces at the end of line, they come from `ConsoleBuffer.Width`. Rendering is still restricted to console width by default (or 80 characters, if console width is unavailable), even when rendering to a text file.

It's possible to set buffer width after measuring and arranging elements (see `ConsoleRenderer.RenderDocumentToBuffer` for the details of the process), but unless you have very specific needs (like completely unrestricted width), I think it's much easier to just trim the whitespace characters afterwards.

You'll need to trim whitespace either way as, say, paragraphs of text would still have trailing whitespace, even when rendered the exactly sized `ConsoleBuffer`, because buffers are always rectangular.

By the way, `ConsoleRenderer.RenderDocumentToText` returns the final string.

**Comment by DumboJetEngine** [comment]
Aha!
Thanks a  lot. :)
I didn't know  couldn't reuse the document.
